name: CICD

on:
  push:
    branches:
      - deploy-to-ec2

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test --watchAll

  build:
    needs: test
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Build Docker Image
        run: docker build -t matteodcr/mgl869 .
      - name: Publish image to Docker Hub
        run: docker push matteodcr/mgl869:latest

      # New steps for GitHub Packages
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/mgl869:latest
            ghcr.io/${{ github.repository }}/mgl869:${{ github.sha }}

  deploy:
    needs: build
    runs-on: aws-ec2
    steps:
      - name: Pull image from Docker Hub
        run: docker pull matteodcr/mgl869
      - name: Delete Old Container
        run: docker rm -f reactContainer
      - name: Run Docker container
        run: docker run -d -p 3000:80 --name reactContainer matteodcr/mgl869